name: Code Coverage

# 暂时禁用此工作流，直到基本构建工作流稳定
# on:
#   push:
#     branches: [ main ]
#   schedule:
#     - cron: '0 0 * * 1'  # 每周一执行一次

# 使用manual触发方式替代自动触发
on: 
  workflow_dispatch:  # 仅允许手动触发

jobs:
  coverage:
    name: 代码覆盖率报告
    runs-on: macos-latest
    
    steps:
    - name: 签出代码
      uses: actions/checkout@v3
    
    - name: 设置Xcode版本
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: 安装依赖
      run: |
        xcodebuild -resolvePackageDependencies
        brew install xcbeautify
    
    - name: 运行测试
      run: |
        xcodebuild test \
          -scheme "Yike" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
          -testPlan "Yike" \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES | xcbeautify 