name: UI Tests

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - 'Yike/**/View*.swift'  # 仅当视图文件更改时触发

jobs:
  ui-test:
    name: 运行UI测试
    runs-on: macos-latest
    
    steps:
    - name: 签出代码
      uses: actions/checkout@v3
    
    - name: 设置Xcode版本
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: 安装依赖
      run: |
        xcodebuild -resolvePackageDependencies
    
    - name: 启用UI测试计划
      run: |
        # 修改测试计划以启用UI测试
        sed -i '' 's/"enabled" : false/"enabled" : true/g' Yike.xctestplan
    
    - name: 运行UI测试
      run: |
        xcodebuild test \
          -scheme "Yike" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
          -testPlan "Yike" \
          -only-testing:YikeUITests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES
    
    - name: 恢复测试计划
      if: always()
      run: |
        # 恢复测试计划到原始状态
        git checkout -- Yike.xctestplan